package dev.ujhhgtg.wekit.features.items.chat

// 豆包 TTS 2.0 内置音色表 (122 个)
val BYTE_DANCE_PRESET_VOICES: List<Pair<String,String>> = listOf(
    "zh_female_vv_uranus_bigtts" to "Vivi 2.0",
    "zh_female_xiaohe_uranus_bigtts" to "小何 2.0",
    "zh_male_m191_uranus_bigtts" to "云舟 2.0",
    "zh_male_taocheng_uranus_bigtts" to "小天 2.0",
    "zh_male_liufei_uranus_bigtts" to "刘飞 2.0",
    "zh_female_sophie_uranus_bigtts" to "魅力苏菲 2.0",
    "zh_female_qingxinnvsheng_uranus_bigtts" to "清新女声 2.0",
    "zh_female_tianmeixiaoyuan_uranus_bigtts" to "甜美小源 2.0",
    "zh_female_tianmeitaozi_uranus_bigtts" to "甜美桃子 2.0",
    "zh_female_shuangkuaisisi_uranus_bigtts" to "爽快思思 2.0",
    "zh_female_linjianvhai_uranus_bigtts" to "邻家女孩 2.0",
    "zh_male_shaonianzixin_uranus_bigtts" to "少年梓辛/Brayan 2.0",
    "zh_female_wenroumama_uranus_bigtts" to "温柔妈妈 2.0",
    "zh_male_jieshuoxiaoming_uranus_bigtts" to "解说小明 2.0",
    "zh_female_tvbnv_uranus_bigtts" to "TVB女声 2.0",
    "zh_male_yizhipiannan_uranus_bigtts" to "译制片男 2.0",
    "zh_female_qiaopinv_uranus_bigtts" to "俏皮女声 2.0",
    "zh_male_linjiananhai_uranus_bigtts" to "邻家男孩 2.0",
    "zh_male_ruyaqingnian_uranus_bigtts" to "儒雅青年 2.0",
    "zh_male_wennuanahu_uranus_bigtts" to "温暖阿虎/Alvin 2.0",
    "zh_male_naiqimengwa_uranus_bigtts" to "奶气萌娃 2.0",
    "zh_female_popo_uranus_bigtts" to "婆婆 2.0",
    "zh_female_gaolengyujie_uranus_bigtts" to "高冷御姐 2.0",
    "zh_male_aojiaobazong_uranus_bigtts" to "傲娇霸总 2.0",
    "zh_male_fanjuanqingnian_uranus_bigtts" to "反卷青年 2.0",
    "zh_female_wenroushunv_uranus_bigtts" to "温柔淑女 2.0",
    "zh_male_huolixiaoge_uranus_bigtts" to "活力小哥 2.0",
    "zh_female_mengyatou_uranus_bigtts" to "萌丫头/Cutey 2.0",
    "zh_female_tiexinnvsheng_uranus_bigtts" to "贴心女声/Candy 2.0",
    "zh_female_jitangmei_uranus_bigtts" to "鸡汤妹妹/Hope 2.0",
    "zh_male_cixingjieshuonan_uranus_bigtts" to "磁性解说男声/Morgan 2.0",
    "zh_male_liangsangmengzai_uranus_bigtts" to "亮嗓萌仔 2.0",
    "zh_female_kailangjiejie_uranus_bigtts" to "开朗姐姐 2.0",
    "zh_male_gaolengchenwen_uranus_bigtts" to "高冷沉稳 2.0",
    "zh_male_shenyeboke_uranus_bigtts" to "深夜播客 2.0",
    "zh_female_jiaochuannv_uranus_bigtts" to "娇喘女声 2.0",
    "zh_female_qinqienv_uranus_bigtts" to "亲切女声 2.0",
    "zh_male_kuailexiaodong_uranus_bigtts" to "快乐小东 2.0",
    "zh_male_kailangxuezhang_uranus_bigtts" to "开朗学长 2.0",
    "zh_male_youyoujunzi_uranus_bigtts" to "悠悠君子 2.0",
    "zh_female_wenjingmaomao_uranus_bigtts" to "文静毛毛 2.0",
    "zh_female_zhixingnv_uranus_bigtts" to "知性女声 2.0",
    "zh_male_qingshuangnanda_uranus_bigtts" to "清爽男大 2.0",
    "zh_male_yuanboxiaoshu_uranus_bigtts" to "渊博小叔 2.0",
    "zh_male_yangguangqingnian_uranus_bigtts" to "阳光青年 2.0",
    "zh_female_qingchezizi_uranus_bigtts" to "清澈梓梓 2.0",
    "zh_female_tianmeiyueyue_uranus_bigtts" to "甜美悦悦 2.0",
    "zh_female_xinlingjitang_uranus_bigtts" to "心灵鸡汤 2.0",
    "zh_male_wenrouxiaoge_uranus_bigtts" to "温柔小哥 2.0",
    "zh_female_roumeinvyou_uranus_bigtts" to "柔美女友 2.0",
    "zh_male_dongfanghaoran_uranus_bigtts" to "东方浩然 2.0",
    "zh_female_wenrouxiaoya_uranus_bigtts" to "温柔小雅 2.0",
    "zh_male_tiancaitongsheng_uranus_bigtts" to "天才童声 2.0",
    "zh_male_guanggaojieshuo_uranus_bigtts" to "广告解说 2.0",
    "zh_female_meilinvyou_uranus_bigtts" to "魅力女友 2.0",
    "zh_female_chanmeinv_uranus_bigtts" to "谄媚女声 2.0",
    "zh_male_kailangdidi_uranus_bigtts" to "开朗弟弟 2.0",
    "zh_female_cancan_uranus_bigtts" to "知性灿灿 2.0",
    "zh_female_sajiaoxuemei_uranus_bigtts" to "撒娇学妹 2.0",
    "zh_female_zhishuaiyingzi_uranus_bigtts" to "直率英子 2.0",
    "zh_male_silang_uranus_bigtts" to "四郎 2.0",
    "zh_male_qingcang_uranus_bigtts" to "擎苍 2.0",
    "zh_male_xionger_uranus_bigtts" to "熊二 2.0",
    "zh_female_yingtaowanzi_uranus_bigtts" to "樱桃丸子 2.0",
    "zh_male_lanyinmianbao_uranus_bigtts" to "懒音绵宝 2.0",
    "zh_female_gufengshaoyu_uranus_bigtts" to "古风少御 2.0",
    "zh_male_lubanqihao_uranus_bigtts" to "鲁班七号 2.0",
    "zh_female_linxiao_uranus_bigtts" to "林潇 2.0",
    "zh_female_lingling_uranus_bigtts" to "玲玲姐姐 2.0",
    "zh_female_chunribu_uranus_bigtts" to "春日部姐姐 2.0",
    "zh_male_tangseng_uranus_bigtts" to "唐僧 2.0",
    "zh_male_zhuangzhou_uranus_bigtts" to "庄周 2.0",
    "zh_male_zhubajie_uranus_bigtts" to "猪八戒 2.0",
    "zh_female_ganmaodianyin_uranus_bigtts" to "感冒电音姐姐 2.0",
    "zh_female_nvleishen_uranus_bigtts" to "女雷神 2.0",
    "zh_female_wuzetian_uranus_bigtts" to "武则天 2.0",
    "zh_female_gujie_uranus_bigtts" to "顾姐 2.0",
    "saturn_zh_female_tiaopigongzhu_tob" to "调皮公主",
    "saturn_zh_male_shuanglangshaonian_tob" to "爽朗少年",
    "saturn_zh_male_tiancaitongzhuo_tob" to "天才同桌",
    "saturn_zh_female_cancan_tob" to "知性灿灿(Saturn)",
    "saturn_zh_female_aojiaonvyou_tob" to "傲娇女友 2.0(Saturn)",
    "saturn_zh_female_bingjiaojiejie_tob" to "病娇姐姐 2.0(Saturn)",
    "saturn_zh_female_chengshujiejie_tob" to "成熟姐姐 2.0(Saturn)",
    "saturn_zh_female_keainvsheng_tob" to "可爱女生 2.0(Saturn)",
    "saturn_zh_female_nuanxinxuejie_tob" to "暖心学姐 2.0(Saturn)",
    "saturn_zh_female_tiexinnvyou_tob" to "贴心女友 2.0(Saturn)",
    "saturn_zh_female_wumeiyujie_tob" to "妩媚御姐 2.0(Saturn)",
    "saturn_zh_female_xingganyujie_tob" to "性感御姐 2.0(Saturn)",
    "saturn_zh_male_aiqilingren_tob" to "傲气凌人 2.0(Saturn)",
    "saturn_zh_male_aojiaogongzi_tob" to "傲娇公子 2.0(Saturn)",
    "saturn_zh_male_aojiaojingying_tob" to "傲娇精英 2.0(Saturn)",
    "saturn_zh_male_aomanshaoye_tob" to "傲慢少爷 2.0(Saturn)",
    "saturn_zh_male_badaoshaoye_tob" to "霸道少爷 2.0(Saturn)",
    "saturn_zh_male_bingjiaobailian_tob" to "病娇白莲 2.0(Saturn)",
    "saturn_zh_male_bujiqingnian_tob" to "不羁青年 2.0(Saturn)",
    "saturn_zh_male_chengshuzongcai_tob" to "成熟总裁 2.0(Saturn)",
    "saturn_zh_male_cixingnansang_tob" to "磁性男嗓 2.0(Saturn)",
    "saturn_zh_male_cujingnanyou_tob" to "醋精男友 2.0(Saturn)",
    "saturn_zh_male_fengfashaonian_tob" to "风发少年 2.0(Saturn)",
    "saturn_zh_male_fuheigongzi_tob" to "腹黑公子 2.0(Saturn)",
    "zh_female_peiqi_uranus_bigtts" to "佩奇猪 2.0",
    "zh_male_sunwukong_uranus_bigtts" to "猴哥 2.0",
    "zh_male_dayi_uranus_bigtts" to "大壹 2.0",
    "zh_female_mizai_uranus_bigtts" to "黑猫侦探社咪仔 2.0",
    "zh_female_jitangnv_uranus_bigtts" to "鸡汤女 2.0",
    "zh_female_liuchangnvsheng_uranus_bigtts" to "流畅女声 2.0",
    "zh_male_ruyayichen_uranus_bigtts" to "儒雅逸辰 2.0",
    "zh_female_xiaoxue_uranus_bigtts" to "儿童绘本 2.0",
    "zh_male_baqiqingshu_uranus_bigtts" to "霸气青叔 2.0",
    "zh_male_xuanyijieshuo_uranus_bigtts" to "悬疑解说 2.0",
    "zh_female_shaoergushi_uranus_bigtts" to "少儿故事 2.0",
    "zh_female_yingyujiaoxue_uranus_bigtts" to "Tina老师 2.0",
    "zh_female_kefunvsheng_uranus_bigtts" to "暖阳女声 2.0",
    "saturn_zh_female_qingyingduoduo_cs_tob" to "轻盈朵朵 2.0(Saturn)",
    "saturn_zh_female_wenwanshanshan_cs_tob" to "温婉珊珊 2.0(Saturn)",
    "saturn_zh_female_reqingaina_cs_tob" to "热情艾娜 2.0(Saturn)",
    "saturn_zh_male_qingxinmumu_cs_tob" to "清新沐沐 2.0(Saturn)",
    "en_male_tim_uranus_bigtts" to "Tim",
    "en_female_dacey_uranus_bigtts" to "Dacey",
    "en_female_stokie_uranus_bigtts" to "Stokie",
    "saturn_zh_female_wenrouwenya_tob" to "温柔文雅 2.0(Saturn)",
)
